[phases.setup]
nixPkgs = ["nodejs_20", "chromium"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = [
  "DATABASE_URL=postgresql://build:build@localhost:5432/rowgram_build npx prisma generate",
  "DATABASE_URL=postgresql://build:build@localhost:5432/rowgram_build npx vinxi build"
]

[start]
cmd = "npm run start"