[phases.setup]
nixPkgs = ["nodejs_20", "chromium"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["DATABASE_URL=postgresql://dummy:dummy@localhost:5432/dummy npm run build"]

[start]
cmd = "npm run start"